<?php

// Constants defining parts of the H2OScore API
define('H2OSCORE_BASE_URL', 'http://www.h2oscore.com');
define('H2OSCORE_REQUEST_TOKEN_URL', H2OSCORE_BASE_URL . '/oauth/request_token');
define('H2OSCORE_AUTHORIZE_URL', H2OSCORE_BASE_URL . '/oauth/authorize');
define('H2OSCORE_ACCESS_TOKEN_URL', H2OSCORE_BASE_URL . '/oauth/access_token');
define('H2OSCORE_API_URL', H2OSCORE_BASE_URL . '/api/v1');

